modLoader="lowcodefml" #mandatory
loaderVersion="${forge_loader_version_range}" #mandatory
license="${license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile = "${mod_id}.png"
authors = "${mod_author}"
description = '''${description}'''
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
